DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS friends_group;

CREATE TABLE friends_group (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name TEXT NOT NULL
);

CREATE TABLE person (
  id INTEGER PRIMARY KEY AUTOINCREMENT,  
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  group_id INTEGER NOT NULL,
  FOREIGN KEY (group_id) REFERENCES friends_group(id)
);